-- Seed: Predefined report templates
-- Description: Insert default PDF templates with pdfmake definitions
-- Created: 2026-02-07

-- Formal Business Template
INSERT INTO report_templates (name, description, template_definition, styles) VALUES (
  'Formal Business',
  'Professional formal report template suitable for corporate clients',
  '{
    "pageSize": "A4",
    "pageMargins": [60, 80, 60, 60],
    "header": {
      "margin": [60, 40, 60, 0],
      "columns": [
        { "text": "WORK REPORT", "style": "header" }
      ]
    },
    "content": [
      {
        "columns": [
          { "text": "Date: {{reportDate}}", "width": "*" },
          { "text": "Location: {{location}}", "width": "*", "alignment": "right" }
        ],
        "margin": [0, 0, 0, 20]
      },
      {
        "text": "Company Information",
        "style": "sectionHeader"
      },
      {
        "columns": [
          [
            { "text": "Company Name:", "bold": true },
            { "text": "{{companyName}}", "margin": [0, 0, 0, 10] },
            { "text": "Tax Number:", "bold": true },
            { "text": "{{taxNumber}}", "margin": [0, 0, 0, 10] },
            { "text": "City:", "bold": true },
            { "text": "{{city}}" }
          ],
          [
            { "text": "Worker:", "bold": true },
            { "text": "{{workerName}}" }
          ]
        ],
        "columnGap": 20,
        "margin": [0, 10, 0, 20]
      },
      {
        "text": "{{introText}}",
        "margin": [0, 0, 0, 20]
      },
      {
        "text": "Work Summary",
        "style": "sectionHeader"
      },
      "{{activitiesTable}}",
      {
        "text": "{{outroText}}",
        "margin": [0, 20, 0, 0]
      }
    ]
  }',
  '{
    "header": {
      "fontSize": 20,
      "bold": true,
      "color": "#2c3e50"
    },
    "sectionHeader": {
      "fontSize": 14,
      "bold": true,
      "margin": [0, 10, 0, 10],
      "color": "#34495e"
    }
  }'
);

-- Modern Minimalist Template
INSERT INTO report_templates (name, description, template_definition, styles) VALUES (
  'Modern Minimalist',
  'Clean and simple modern design with minimal styling',
  '{
    "pageSize": "A4",
    "pageMargins": [40, 60, 40, 60],
    "content": [
      {
        "text": "WORK REPORT",
        "style": "title",
        "margin": [0, 0, 0, 30]
      },
      {
        "columns": [
          [
            { "text": "{{reportDate}}", "style": "subtitle" },
            { "text": "{{location}}", "style": "subtitle" }
          ],
          [
            { "text": "{{companyName}}", "style": "subtitle", "alignment": "right" },
            { "text": "{{city}}", "style": "subtitle", "alignment": "right" }
          ]
        ],
        "margin": [0, 0, 0, 20]
      },
      {
        "canvas": [
          {
            "type": "line",
            "x1": 0,
            "y1": 0,
            "x2": 515,
            "y2": 0,
            "lineWidth": 1,
            "lineColor": "#cccccc"
          }
        ],
        "margin": [0, 0, 0, 20]
      },
      {
        "text": "{{introText}}",
        "margin": [0, 0, 0, 20],
        "alignment": "justify"
      },
      {
        "text": "Prepared by: {{workerName}}",
        "margin": [0, 0, 0, 20],
        "italics": true
      },
      "{{activitiesTable}}",
      {
        "text": "{{outroText}}",
        "margin": [0, 20, 0, 0],
        "alignment": "justify"
      }
    ]
  }',
  '{
    "title": {
      "fontSize": 24,
      "bold": true,
      "color": "#000000"
    },
    "subtitle": {
      "fontSize": 10,
      "color": "#666666"
    }
  }'
);

-- Detailed Professional Template
INSERT INTO report_templates (name, description, template_definition, styles) VALUES (
  'Detailed Professional',
  'Comprehensive template with detailed company information and structured layout',
  '{
    "pageSize": "A4",
    "pageMargins": [50, 70, 50, 70],
    "header": {
      "columns": [
        { "text": " ", "width": "*" },
        {
          "stack": [
            { "text": "MONTHLY WORK REPORT", "style": "headerText" },
            { "text": "{{reportDate}}", "style": "headerSubtext" }
          ],
          "width": "auto"
        },
        { "text": " ", "width": "*" }
      ],
      "margin": [50, 30, 50, 0]
    },
    "footer": {
      "columns": [
        { "text": "Generated by Freelancer Report System", "alignment": "left", "fontSize": 8, "color": "#999999" },
        { "text": "Page {{currentPage}} of {{pageCount}}", "alignment": "right", "fontSize": 8, "color": "#999999" }
      ],
      "margin": [50, 10, 50, 0]
    },
    "content": [
      {
        "table": {
          "widths": ["*"],
          "body": [
            [
              {
                "stack": [
                  { "text": "CLIENT INFORMATION", "style": "tableHeader" },
                  {
                    "columns": [
                      [
                        { "text": "Company:", "bold": true, "margin": [0, 5, 0, 0] },
                        { "text": "{{companyName}}", "margin": [0, 2, 0, 0] },
                        { "text": "Tax ID:", "bold": true, "margin": [0, 5, 0, 0] },
                        { "text": "{{taxNumber}}", "margin": [0, 2, 0, 0] }
                      ],
                      [
                        { "text": "Location:", "bold": true, "margin": [0, 5, 0, 0] },
                        { "text": "{{city}}, {{location}}", "margin": [0, 2, 0, 0] }
                      ]
                    ],
                    "columnGap": 30,
                    "margin": [10, 10, 10, 10]
                  }
                ],
                "fillColor": "#f5f5f5"
              }
            ]
          ]
        },
        "margin": [0, 0, 0, 20]
      },
      {
        "table": {
          "widths": ["*"],
          "body": [
            [
              {
                "stack": [
                  { "text": "FREELANCER", "style": "tableHeader" },
                  { "text": "{{workerName}}", "margin": [10, 10, 10, 10], "fontSize": 12 }
                ],
                "fillColor": "#f5f5f5"
              }
            ]
          ]
        },
        "margin": [0, 0, 0, 20]
      },
      {
        "text": "{{introText}}",
        "margin": [0, 0, 0, 20],
        "alignment": "justify"
      },
      {
        "text": "WORK DETAILS",
        "style": "sectionTitle",
        "margin": [0, 10, 0, 10]
      },
      "{{activitiesTable}}",
      {
        "text": "{{outroText}}",
        "margin": [0, 30, 0, 0],
        "alignment": "justify"
      }
    ]
  }',
  '{
    "headerText": {
      "fontSize": 16,
      "bold": true,
      "alignment": "center",
      "color": "#2c3e50"
    },
    "headerSubtext": {
      "fontSize": 10,
      "alignment": "center",
      "color": "#7f8c8d",
      "margin": [0, 5, 0, 0]
    },
    "tableHeader": {
      "fontSize": 11,
      "bold": true,
      "color": "#2c3e50",
      "margin": [10, 10, 10, 5]
    },
    "sectionTitle": {
      "fontSize": 14,
      "bold": true,
      "color": "#34495e"
    }
  }'
);
